name: Fudan Daily

on:
  schedule:
    - cron: '40 00 * * 0'
    - cron: '23 00 * * 1'
    - cron: '54 00 * * 2'
    - cron: '23 00 * * 3'
    - cron: '12 00 * * 4'
    - cron: '16 00 * * 5'
    - cron: '52 00 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests
      - name: Run app
        run: python TsingHuaDaily.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
